name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  RUFF_OUTPUT_FORMAT: "github"

jobs:
  run:
    name: test with ${{ matrix.env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        env: ["3.15", "3.14", "3.13", "3.12", "3.11", "3.10", "3.9", "3.8"]
        include:
          - os: windows-latest
            env: "3.14"
          - os: macos-latest
            env: "3.14"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: false
      - name: Install tox
        run: >-
          uv tool install
          --python-preference only-managed
          --python 3.14
          tox
          --with tox-uv
          --with tox-gh
      - name: Install Python
        if: matrix.env != '3.14'
        run: >-
          uv python install
          --python-preference only-managed
          ${{ matrix.env }}
      - name: Setup test suite
        run: tox run -vv --notest --skip-missing-interpreters false
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
      - name: Run test suite
        run: tox run --skip-pkg-install
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
